# found text from LibriTTS
text_inputs = [ 
    # FROM `1272_128104.book.tsv`
    'Mr. Quilter is the apostle of the middle classes, and we are glad to welcome his gospel.',
    "Nor is Mr. Quilter's manner less interesting than his matter.",
    "He tells us that at this festive season of the year, with Christmas and roast beef looming before us, 'Similes drawn from eating and its results occur most readily to the mind.'",
    "He has grave doubts whether Sir Frederick Leighton's work is really 'Greek, after all,' and can discover in it but little of 'rocky Ithaca.'",
    "Linnell's pictures, are 'a sort of \"Up, Guards, and at 'em\" paintings,' and Mason's exquisite idylls are 'as national as a Jingo poem'! Mr. Birket Foster's landscapes 'smile at one much in the same way that Mr. Carker used to \"flash his teeth,\"' and Mr. John Collier gives his sitter 'a cheerful slap on the back, before he says, like a shampooer in a Turkish bath, \"Next man!\"",
    "It is obviously unnecessary for us to point out how luminous these criticisms are, how delicate in expression.",
    "On the general principles of art Mr. Quilter writes with equal lucidity.",
    "Painting, he tells us, is 'of a different quality to mathematics,' and finish in art is 'adding more fact'!",
    "As for etchings, they are of two kinds--British and foreign.",
    "He laments most bitterly the divorce that has been made between decorative art and 'what we usually call \"pictures,\"' makes the customary appeal to the Last Judgment, and reminds us that in the great days of art Michael Angelo was the 'furnishing upholsterer.'",
    "near the fire, and the ornaments Fred brought home from India on the mantel-board'!",
    "In fact, he is quite severe on Mr. Ruskin for not recognising that 'a picture should denote the frailty of man,' and remarks with pleasing courtesy and felicitous grace that 'many phases of feeling . . . ",
    "Only, unfortunately, his own work never does get good.",
    "Mr. Quilter has missed his chance; for he has failed even to make himself the Tupper of Painting.",
    "By Harry Quilter, M.A.",
    # FROM `1272_135031.book.tsv`
    "\"Because you were sleeping instead of conquering, the lovely Rose Princess has become a fiddle without a bow, while poor Shaggy sits there a cooing dove!\"",
    "\"He has gone, and gone for good,\" answered Polychrome, who had managed to squeeze into the room beside the dragon and had witnessed the occurrences with much interest.",
    '"I have remained a prisoner only because I wished to be one," and with this he stepped forward and burst the stout chains as easily as if they had been threads.',
    "The little girl had been asleep, but she heard the raps and opened the door.",
    '"The King has fled in disgrace and your friends are asking for you."',
    '"I begged Ruggedo long ago to send him away, but he would not do so."',
    '"I also offered to help your brother to escape, but he would not go."',
    '"He eats and sleeps very steadily," replied the new King.',
    '"I hope he doesn\'t work too hard," said Shaggy.',
    '"He doesn\'t work at all."',
    "In fact, there is nothing he can do in these dominions as well as our nomes, whose numbers are so great that it worries us to keep them all busy.",
    '"Not exactly," returned Kaliko.',
    '"Where is my brother now?"',
    'inquired Shaggy. "In the Metal Forest."',
    '"Where is that?"',
    '"The Metal Forest is in the Great Domed Cavern, the largest in all our dominions," replied Kaliko.',
    'Kaliko hesitated.',
    '"However, if we look sharp, we may be able to discover one of these secret ways."',
    '"Oh, no; I\'m quite sure he didn\'t."',
    '"That\'s funny," remarked Betsy thoughtfully.',
    '"I don\'t believe Ann knew any magic, or she\'d have worked it before."',
    '"I do not know," confessed Shaggy.',
    '"True," agreed Kaliko.',
    'Kaliko went to the big gong and pounded on it just as Ruggedo used to do; but no one answered the summons.',
    "Having returned to the royal cavern, Kaliko first pounded the gong and then sat in the throne, wearing Ruggedo's discarded ruby crown and holding in his hand the sceptre which Ruggedo had so often thrown at his head.",
    # FROM `1272_141231.book.tsv`
    '_A man said to the universe: "Sir, I exist!"',
    "Sweat covered Brion's body, trickling into the tight loincloth that was the only garment he wore.",
    'The cut on his chest, still dripping blood, the ache of his overstrained eyes--even the soaring arena around him with the thousands of spectators--were trivialities not worth thinking about.',
    'His instant of panic was followed by a small sharp blow high on his chest.',
    '"One minute," a voice said, and the time buzzer sounded.',
    'A minute is not a very large measure of time and his body needed every fraction of it.',
    "The buzzer's whirr triggered his muscles into complete relaxation.",
    'Only his heart and lungs worked on at a strong, measured rate.',
    'He was in reverie, sliding along the borders of consciousness.',
    'The contestants in the Twenties needed undisturbed rest, therefore nights in the dormitories were as quiet as death.',
    'Particularly so on this last night, when only two of the little cubicles were occupied, the thousands of others standing with dark, empty doors.',
    'The other voice snapped with a harsh urgency, clearly used to command.',
    '"I\'m here because the matter is of utmost importance, and Brandd is the one I must see. Now stand aside!"',
    '"The Twenties--"',
    'He must have drawn his gun, because the intruder said quickly, "Put that away. You\'re being a fool!"',
    'There was silence then and, still wondering, Brion was once more asleep.',
    '"Ten seconds."',
    'he asked the handler who was kneading his aching muscles.',
    'A red-haired mountain of a man, with an apparently inexhaustible store of energy.',
    'There could be little art in this last and final round of fencing.',
    'Just thrust and parry, and victory to the stronger.',
    'Every man who entered the Twenties had his own training tricks.',
    'There appeared to be an immediate association with the death-trauma, as if the two were inextricably linked into one.',
    'The strength that enables someone in a trance to hold his body stiff and unsupported except at two points, the head and heels',
    'This is physically impossible when conscious.',
    'Others had died before during the Twenties, and death during the last round was in some ways easier than defeat.',
    'Breathing deeply, Brion softly spoke the auto-hypnotic phrases that triggered the process.',
    "When the buzzer sounded he pulled his foil from his second's startled grasp, and ran forward.",
    'Irolg looked amazed at the sudden fury of the attack--then smiled.',
    'He thought it was a last burst of energy, he knew how close they both were to exhaustion.',
    "Brion saw something close to panic on his opponent's face when the man finally recognized his error.",
    'A wave of despair rolled out from Irolg--Brion sensed it and knew the fifth point was his.',
    'Then the powerful twist that thrust it aside. In and under the guard.'
    ]